"""Core interface building blocks for embodia."""

from .config_keys import MethodAliasKey, ModelSpecKey, RobotSpecKey
from .config_io import load_component_yaml_config
from .errors import InterfaceValidationError
from .mixins import ModelMixin, RobotMixin
from .modalities import (
    COMMAND_KINDS,
    CONTROL_TARGETS,
    IMAGE_KEYS,
    STATE_KEYS,
    ModalityToken,
)
from .protocols import ModelProtocol, RobotProtocol
from .schema import (
    Action,
    COMMAND_KIND_REGISTRY,
    CUSTOM_COMMAND_KIND_PREFIX,
    Command,
    CommandKindSpec,
    ControlGroupSpec,
    Frame,
    KNOWN_CONTROL_GROUP_KINDS,
    ModelOutputSpec,
    ModelSpec,
    RobotSpec,
    get_command_kind_spec,
    is_custom_command_kind_name,
    is_known_command_kind,
    register_command_kind,
)
from .transform import (
    action_to_dict,
    coerce_action,
    coerce_command,
    coerce_control_group_spec,
    coerce_frame,
    coerce_model_output_spec,
    coerce_model_spec,
    coerce_robot_spec,
    command_to_dict,
    control_group_spec_to_dict,
    frame_to_dict,
    invert_mapping,
    model_output_spec_to_dict,
    model_spec_to_dict,
    remap_action,
    remap_command,
    remap_control_group_spec,
    remap_frame,
    remap_mapping_keys,
    remap_model_output_spec,
    remap_model_spec,
    remap_robot_spec,
    robot_spec_to_dict,
)

__all__ = [
    "Action",
    "COMMAND_KIND_REGISTRY",
    "COMMAND_KINDS",
    "CONTROL_TARGETS",
    "CUSTOM_COMMAND_KIND_PREFIX",
    "Command",
    "CommandKindSpec",
    "ControlGroupSpec",
    "Frame",
    "IMAGE_KEYS",
    "InterfaceValidationError",
    "KNOWN_CONTROL_GROUP_KINDS",
    "MethodAliasKey",
    "ModelMixin",
    "ModelOutputSpec",
    "ModelProtocol",
    "ModelSpecKey",
    "ModelSpec",
    "RobotMixin",
    "RobotProtocol",
    "RobotSpecKey",
    "RobotSpec",
    "ModalityToken",
    "STATE_KEYS",
    "action_to_dict",
    "coerce_action",
    "coerce_command",
    "coerce_control_group_spec",
    "coerce_frame",
    "coerce_model_output_spec",
    "coerce_model_spec",
    "coerce_robot_spec",
    "command_to_dict",
    "control_group_spec_to_dict",
    "frame_to_dict",
    "get_command_kind_spec",
    "invert_mapping",
    "is_custom_command_kind_name",
    "is_known_command_kind",
    "load_component_yaml_config",
    "model_output_spec_to_dict",
    "model_spec_to_dict",
    "remap_action",
    "remap_command",
    "remap_control_group_spec",
    "remap_frame",
    "remap_mapping_keys",
    "remap_model_output_spec",
    "remap_model_spec",
    "remap_robot_spec",
    "register_command_kind",
    "robot_spec_to_dict",
]
