"""Core interface building blocks for embodia."""

from .config_keys import MethodAliasKey, PolicySpecKey, RobotSpecKey
from .config_io import load_component_yaml_config
from .errors import InterfaceValidationError
from .mixins import PolicyMixin, RobotMixin
from .modalities import (
    COMMAND_KINDS,
    CONTROL_TARGETS,
    IMAGE_KEYS,
    STATE_KEYS,
    ModalityToken,
)
from .protocols import ChunkPolicyProtocol, PolicyProtocol, RobotProtocol
from .schema import (
    Action,
    COMMAND_KIND_REGISTRY,
    CUSTOM_COMMAND_KIND_PREFIX,
    ComponentSpec,
    Command,
    CommandKindSpec,
    Frame,
    KNOWN_COMPONENT_TYPES,
    PolicyOutputSpec,
    PolicySpec,
    RobotSpec,
    get_command_kind_spec,
    is_custom_command_kind_name,
    is_known_command_kind,
    register_command_kind,
)
from .transform import (
    action_to_dict,
    component_spec_to_dict,
    coerce_action,
    coerce_command,
    coerce_component_spec,
    coerce_frame,
    coerce_policy_output_spec,
    coerce_policy_spec,
    coerce_robot_spec,
    command_to_dict,
    frame_to_dict,
    invert_mapping,
    policy_output_spec_to_dict,
    policy_spec_to_dict,
    remap_action,
    remap_command,
    remap_component_spec,
    remap_frame,
    remap_mapping_keys,
    remap_policy_output_spec,
    remap_policy_spec,
    remap_robot_spec,
    robot_spec_to_dict,
)

__all__ = [
    "Action",
    "COMMAND_KIND_REGISTRY",
    "COMMAND_KINDS",
    "ChunkPolicyProtocol",
    "CONTROL_TARGETS",
    "CUSTOM_COMMAND_KIND_PREFIX",
    "ComponentSpec",
    "Command",
    "CommandKindSpec",
    "Frame",
    "IMAGE_KEYS",
    "InterfaceValidationError",
    "KNOWN_COMPONENT_TYPES",
    "MethodAliasKey",
    "PolicyMixin",
    "PolicyOutputSpec",
    "PolicyProtocol",
    "PolicySpecKey",
    "PolicySpec",
    "RobotMixin",
    "RobotProtocol",
    "RobotSpecKey",
    "RobotSpec",
    "ModalityToken",
    "STATE_KEYS",
    "action_to_dict",
    "component_spec_to_dict",
    "coerce_action",
    "coerce_command",
    "coerce_component_spec",
    "coerce_frame",
    "coerce_policy_output_spec",
    "coerce_policy_spec",
    "coerce_robot_spec",
    "command_to_dict",
    "frame_to_dict",
    "get_command_kind_spec",
    "invert_mapping",
    "is_custom_command_kind_name",
    "is_known_command_kind",
    "load_component_yaml_config",
    "policy_output_spec_to_dict",
    "policy_spec_to_dict",
    "remap_action",
    "remap_command",
    "remap_component_spec",
    "remap_frame",
    "remap_mapping_keys",
    "remap_policy_output_spec",
    "remap_policy_spec",
    "remap_robot_spec",
    "register_command_kind",
    "robot_spec_to_dict",
]
